version: "3"
services:
  redis-source:
    container_name: "redis-source" # used in sentinel.conf
    image: redis:6.0-alpine
    command: redis-server
    ports:
      - "6379:6379"
  dragonfly:
    container_name: "dragonfly"
    image: "ghcr.io/dragonflydb/dragonfly:v1.10.0-ubuntu"
    ulimits:
      memlock: -1
    ports:
      - "6380:6379"
    command:
      - "--dir=/data"
  sentinel-1:
    container_name: "sentinel-1"
    image: redis:6.0-alpine
    ports:
      - "5001:5000"
    command: redis-server /etc/redis-config/sentinel.conf --sentinel
    volumes:
      - "./config/sentinel-1:/etc/redis-config"
  sentinel-2:
    container_name: "sentinel-2"
    image: redis:6.0-alpine
    ports:
      - "5002:5000"
    command: redis-server /etc/redis-config/sentinel.conf --sentinel
    volumes:
      - "./config/sentinel-2:/etc/redis-config"
  sentinel-3:
    container_name: "sentinel-3"
    image: redis:6.0-alpine
    ports:
      - "5003:5000"
    command: redis-server /etc/redis-config/sentinel.conf --sentinel
    volumes:
      - "./config/sentinel-3:/etc/redis-config"
  leaderboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leaderboard
    ports:
      - "8080:8080"
